---
- name: Creating users and group
  hosts: localhost
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: creating a group
      group:
        name: test
        state: present
      register: Group_details

    - name: To display group details   
      debug:
        msg: "{{ Group_details }}"

    - name: creating a user
      user:
        name: anil
        state: present
        groups: test
        group: test
      register: User_details


    - name: To display user details
      debug:
        msg: "{{ User_details }}"

    - name: checking groups
      shell: "groups anil"
      register: user

    - name: to display user
      debug:
        msg: "{{ user }}"
...
